import { apiRequest } from './client';

export interface NotificationItem {
  id: string;
  _id?: string;
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error' | 'promo' | 'alert';
  isRead: boolean;
  time?: string;
  createdAt?: string;
  actionUrl?: string;
}

export const FALLBACK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Brand DNA Complete',
    message: 'Voice tone, content pillars & memory synthesized for ZIVA.',
    type: 'success',
    isRead: false,
    time: '10m ago',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif_2',
    title: 'Campaign Ready for Review',
    message: 'Q3 Product Acceleration has 14 AI-generated creatives ready for review.',
    type: 'info',
    isRead: false,
    time: '45m ago',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif_3',
    title: 'New AI Content Generated',
    message: '6 new Instagram carousel drafts and reels generated by AISA.',
    type: 'promo',
    isRead: false,
    time: '2h ago',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif_4',
    title: 'Approval Required',
    message: 'Video ad draft "Summer Flash Sale" requires director sign-off.',
    type: 'alert',
    isRead: true,
    time: '5h ago',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif_5',
    title: 'Subscription Active',
    message: 'Agency Pro tier renewed. 500 AI credits ready in your wallet.',
    type: 'success',
    isRead: true,
    time: '1d ago',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
];

export const notificationApi = {
  getNotifications: async (userId?: string): Promise<{ success: boolean; notifications: NotificationItem[] }> => {
    try {
      const res = await apiRequest<{ success: boolean; notifications?: NotificationItem[] }>(
        userId ? `/notifications?userId=${userId}&limit=20` : '/notifications?limit=20',
        { method: 'GET' }
      );
      if (res && res.success && Array.isArray(res.notifications) && res.notifications.length > 0) {
        return { success: true, notifications: res.notifications };
      }
      return { success: true, notifications: FALLBACK_NOTIFICATIONS };
    } catch {
      return { success: true, notifications: FALLBACK_NOTIFICATIONS };
    }
  },

  markAsRead: async (id: string): Promise<{ success: boolean }> => {
    try {
      return await apiRequest(`/notifications/${id}/read`, { method: 'PATCH' });
    } catch {
      return { success: true };
    }
  },
};
